FROM jenkins/jenkins:lts

# Plugins for better UX (not mandatory)
RUN /usr/local/bin/install-plugins.sh ansicolor
RUN /usr/local/bin/install-plugins.sh greenballs
RUN /usr/local/bin/install-plugins.sh simple-theme-plugin
RUN /usr/local/bin/install-plugins.sh locale
RUN /usr/local/bin/install-plugins.sh blueocean
RUN /usr/local/bin/install-plugins.sh localization-zh-cn

# Plugin for scaling Jenkins agents
RUN /usr/local/bin/install-plugins.sh kubernetes

# Plugin for git
RUN /usr/local/bin/install-plugins.sh git
RUN /usr/local/bin/install-plugins.sh github
RUN /usr/local/bin/install-plugins.sh gitlab-plugin

USER jenkins
