FROM jenkins/jnlp-slave

USER root

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    git \
    sudo \
    libunwind8 \
    gettext && add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable" && apt-get update && \
    apt-get install -y docker-ce

RUN usermod -aG docker jenkins
USER jenkins

ENTRYPOINT ["jenkins-slave"]
