FROM jenkins/jenkins:lts

# Plugins for better UX (not mandatory)
RUN /usr/local/bin/install-plugins.sh ansicolor
RUN /usr/local/bin/install-plugins.sh greenballs

# Plugin for scaling Jenkins agents
RUN /usr/local/bin/install-plugins.sh kubernetes

# Plugin for git
RUN /usr/local/bin/install-plugins.sh git
RUN /usr/local/bin/install-plugins.sh github

USER jenkins
