kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: lvm
